title: Furkan SAYIM
name: Furkan SAYIM
description: Bir Pentester ve Purple Teamer blogudur.
permalink: /:year/:month/:day/:title.html
author: Furkan SAYIM


baseurl: ""
url: "https://furkansayim.com"
lang: "tr"

github_username:  xShuden

social:
    name: Furkan SAYIM
    links:
        - https://twitter.com/xShuden
        - https://github.com/xShuden
